services:
  web:
    build: .
    container_name: demo-django
    ports:
      - "8000:8000"
    userns_mode: keep-id
    volumes:
      - .:/app:z
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
